# Render Blueprint for Backend Deployment
services:
  - type: web
    name: blood-warriors-backend
    env: node
    plan: free # Free tier, upgrade to starter/standard for production
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      # Add your environment variables in Render dashboard
      # Don't put sensitive values here - use Render's Environment Variables section
    healthCheckPath: /api/health

# Auto-deploy settings
buildFilter:
  paths:
    - backend/**
  ignoredPaths:
    - frontend/**
